/**
 * Error codes for admin endpoints. Clients branch on `error.code`, never on
 * the human-readable message. Add a code here before using it.
 */
const ERROR_CODES = Object.freeze({
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  MAINTENANCE: 'MAINTENANCE',

  // Authentication
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_IDLE_TIMEOUT: 'SESSION_IDLE_TIMEOUT',
  TOTP_REQUIRED: 'TOTP_REQUIRED',
  TOTP_INVALID: 'TOTP_INVALID',
  TOTP_NOT_ENROLLED: 'TOTP_NOT_ENROLLED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  TOTP_ENROLMENT_REQUIRED: 'TOTP_ENROLMENT_REQUIRED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  SUPER_ADMIN_REQUIRED: 'SUPER_ADMIN_REQUIRED',
  LAST_SUPER_ADMIN: 'LAST_SUPER_ADMIN',
  SELF_MODIFICATION: 'SELF_MODIFICATION',
  SECOND_APPROVER_REQUIRED: 'SECOND_APPROVER_REQUIRED',

  // Domain
  DELETE_BLOCKED: 'DELETE_BLOCKED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
});

// Default HTTP status for codes that are always the same status.
const DEFAULT_STATUS = Object.freeze({
  VALIDATION_FAILED: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
  MAINTENANCE: 503,
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_DEACTIVATED: 403,
  TOO_MANY_ATTEMPTS: 429,
  TOKEN_INVALID: 401,
  SESSION_REVOKED: 401,
  SESSION_IDLE_TIMEOUT: 401,
  TOTP_REQUIRED: 401,
  TOTP_INVALID: 401,
  TOTP_NOT_ENROLLED: 409,
  PASSWORD_CHANGE_REQUIRED: 403,
  TOTP_ENROLMENT_REQUIRED: 403,
  WEAK_PASSWORD: 400,
  FORBIDDEN: 403,
  SUPER_ADMIN_REQUIRED: 403,
  LAST_SUPER_ADMIN: 409,
  SELF_MODIFICATION: 403,
  SECOND_APPROVER_REQUIRED: 403,
  DELETE_BLOCKED: 409,
  INVALID_TRANSITION: 409,
  INSUFFICIENT_BALANCE: 409,
});

module.exports = { ERROR_CODES, DEFAULT_STATUS };
